version: "3.7"

services:

  mysql:
      image: mysql
      volumes:
        - ./mysql-data:/Applications/XAMPP/xamppfiles/var/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: fstechbb

        
  app:
    image: felipeam/node-fstechbb
    ports: 
     - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: fstechbb

    